### ISSUE TITLE
Vim support

### ISSUE THREAD

**Issue by TamaMcGlinn** [dpretet/vim-leader-mapper#7]
I'm not expecting you to do this, but it's good to have it up here, both to make it more visible that this plugin doesn't support regular vim, and as a place to list the reasons why not, so that someone who wants to do this has a place to start.

So, why doesn't vim-leader-mapper work on regular Vim?

**Comment by dpretet** [comment]
Hi,

the only reason is I use Neovim at full time and so I developed this plugin based on its floating window API. This is clearly possible to support Vim now they implemented popup feature similar to floating window. Maybe I'll do it one day if leader-mapper becomes popular :p 

Damien

**Comment by dpretet** [comment]
Vim support is available :)
